swagger: "2.0"
info:
 title: Auto Shop API
 version: 1.0.0
host: se-mod2-2-1.onrender.com
basePath: /api/v1
schemes:
 - https
securityDefinitions:
 bearerAuth:
  type: apiKey
  name: Authorization
  in: header
security:
 - bearerAuth: []
tags:
 - name: Users
 - name: Service Tickets
 - name: Mechanics
 - name: Inventory
paths:
 /users:
  get:
   tags:
    - Users
   summary: Paginated Users
   parameters:
    - name: page
      in: query
      type: integer
      default: 1
    - name: per_page
      in: query
      type: integer
      default: 10
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /users/register:
  post:
   tags:
    - Users
   summary: Register
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        name:
         type: string
         example: Test User
        email:
         type: string
         example: user@example.com
        password:
         type: string
         example: password123
        phone:
         type: string
         example: 123-456-7890
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /users/my-tickets:
  get:
   tags:
    - Users
   summary: Get Tickets
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /users/login:
  post:
   tags:
    - Users
   summary: Login
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        email:
         type: string
         example: user@example.com
        password:
         type: string
         example: password123
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /users/1:
  put:
   tags:
    - Users
   summary: Update User
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        name:
         type: string
         example: Updated Name
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object
  delete:
   tags:
    - Users
   summary: Delete User
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /service-tickets:
  get:
   tags:
    - Service Tickets
   summary: Paginated Tickets
   parameters:
    - name: page
      in: query
      type: integer
      default: 1
    - name: per_page
      in: query
      type: integer
      default: 10
   responses:
    200:
     description: Successful response
     schema:
      type: object
  post:
   tags:
    - Service Tickets
   summary: Create Ticket
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        title:
         type: string
         example: Test Ticket
        description:
         type: string
         example: Test Description
        status:
         type: string
         example: pending
        priority:
         type: string
         example: normal
        mechanic_ids:
         type: array
         items:
          type: integer
         example: [1]
        part_ids:
         type: array
         items:
          type: integer
         example: [1]
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /service-tickets/1:
  get:
   tags:
    - Service Tickets
   summary: Get Ticket
   responses:
    200:
     description: Successful response
     schema:
      type: object
  put:
   tags:
    - Service Tickets
   summary: Update Ticket
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        VIN:
         type: string
         example: 1HGCM82633A123456
        description:
         type: string
         example: Updated oil change and tire rotation
        service_date:
         type: string
         example: "2024-02-15"
        mechanic_ids:
         type: array
         items:
          type: integer
         example: [1, 2]
        part_ids:
         type: array
         items:
          type: integer
         example: [1, 3]
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object
  delete:
   tags:
    - Service Tickets
   summary: Delete Ticket
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /mechanics:
  get:
   tags:
    - Mechanics
   summary: Paginated Mechanics
   parameters:
    - name: page
      in: query
      type: integer
      default: 1
    - name: per_page
      in: query
      type: integer
      default: 10
   responses:
    200:
     description: Successful response
     schema:
      type: object
  post:
   tags:
    - Mechanics
   summary: Create Mechanic
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        name:
         type: string
         example: John Smith
        specialty:
         type: string
         example: Engine Repair
        email:
         type: string
         example: john@example.com
        phone:
         type: string
         example: 123-456-7890
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /mechanics/1:
  get:
   tags:
    - Mechanics
   summary: Get Mechanic
   responses:
    200:
     description: Successful response
     schema:
      type: object
  put:
   tags:
    - Mechanics
   summary: Update Mechanic
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        salary:
         type: integer
         example: 80000
        phone:
         type: string
         example: 987-654-3210
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object
  delete:
   tags:
    - Mechanics
   summary: Delete Mechanic
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /inventory:
  get:
   tags:
    - Inventory
   summary: Get All Parts
   responses:
    200:
     description: Successful response
     schema:
      type: object
  post:
   tags:
    - Inventory
   summary: Create Part
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        name:
         type: string
         example: Brake Pad
        part_number:
         type: string
         example: BP-2024-001
        price:
         type: number
         example: 45.99
        quantity:
         type: integer
         example: 50
   security:
    - bearerAuth: []
   responses:
    200:
     description: Successful response
     schema:
      type: object

 /inventory/1:
  put:
   tags:
    - Inventory
   summary: Update Part
   parameters:
    - in: body
      name: body
      required: true
      schema:
       type: object
       properties:
        name:
         type: string
         example: Updated Part Name
        part_number:
         type: string
         example: BP-2024-001
        price:
         type: number
         example: 29.99
        quantity:
         type: integer
         example: 50
   responses:
    200:
     description: Successful response
     schema:
      type: object
  delete:
   tags:
    - Inventory
   summary: Delete Part
   responses:
    200:
     description: Successful response
     schema:
      type: object
